DATA:
  BATCH_SIZE: 2
  FILTER:
    MAX_DEPTH: 65
    MAX_OCCLUSION: 2
    MAX_TRUNCATION: 0.5
    MIN_DEPTH: 2
    MIN_HEIGHT: 25
  NUM_WORKERS: 0
  ROOT: dataset
  TEST_SPLIT: val
  TRAIN_SPLIT: train
DESCRIPTION: MonoCon Default Configuration
GPU_ID: 0
MODEL:
  BACKBONE:
    IMAGENET_PRETRAINED: false
    NUM_LAYERS: 34
  HEAD:
    MAX_OBJS: 30
    NUM_CLASSES: 3
OUTPUT_DIR: ''
PERIOD:
  EVAL_PERIOD: 1
  LOG_PERIOD: 50
SEED: 1891176477
SOLVER:
  CLIP_GRAD:
    ENABLE: true
    MAX_NORM: 35
    NORM_TYPE: 2.0
  OPTIM:
    LR: 0.000225
    NUM_EPOCHS: 5
    WEIGHT_DECAY: 1.0e-05
  SCHEDULER:
    ENABLE: true
TRAIN_TYPE: DDP
USE_BENCHMARK: false
VERSION: v1.0.3

